### ISSUE TITLE
Long lines are cut off in vignette PDF

### ISSUE THREAD

**Issue by colinbrislawn** [skembel/picante#13]
I've been working my way through the [picante vignette](https://github.com/skembel/picante/tree/master/vignettes), and found some lines of code which are too long to fit on the PDF page.

![screen shot 2017-09-19 at 3 52 52 pm](https://user-images.githubusercontent.com/10355152/30619196-02c4c2b0-9d53-11e7-932e-6a10bed0177d.png)

Specifically, [Lines 100,](https://github.com/skembel/picante/blob/master/vignettes/picante-intro.Rnw#L100) [145, and 147](https://github.com/skembel/picante/blob/master/vignettes/picante-intro.Rnw#L145-L147) could be wrapped.

The warning from [line 178](https://github.com/skembel/picante/blob/master/vignettes/picante-intro.Rnw#L178) also has this issue, but that's probably less important to include.

Thanks for continuing to support this software package! My colleagues have used it to great success, and I hope to do the same.

Edit: added another line.
Are you accepting pull requests? This seems like a pretty simple fix, but I'm not sure if you are looking for PRs right now.

**Comment by skembel** [comment]
Sorry about the incredibly long delay, I would accept a pull request to fix this, otherwise I will update in the next release of the package.

**Comment by colinbrislawn** [comment]
Hey, thanks!

Did we want to wrap some of the other lines too?
`print("Dropping taxa from the community because they are not present in the phylogeny:")`
Maybe we could change to:
`writeLines("Dropping taxa from the community because \nthey are not present in the phylogeny:")`
or
`cat("Dropping taxa from the community because \nthey are not present in the phylogeny:", "\n")`
