### ISSUE TITLE
Can AITCHISON distance be used in MNTD and MPD calculations?

### ISSUE THREAD

**Issue by Jigyasa3** [skembel/picante#20]
I wanted to ask two questions-
1.  Similar to Phylogenetic beta-diversity calculations, can we use Euclidean or any other distance matrix for MNTD and MPD measurements?

If not, then can we use log-transformed data or log-ratio transformed data instead of counts?

2. A follow up to the #issue I opened before this. If my "comm" data frame is actually AITCHISON distance between species rather than a data frame of species and sites. Would it make sense to perform grouping of monophyletic clades on such a dataset for among species comparison?

Thanks!

**Comment by skembel** [comment]
All of the MPD/MNTD functions will accept any distance matrix as input. It is possible to do this with transformed data or with any distance measure including Aitchison distance. However, I am not aware of any work that has quantified the suitability of the Aitchison distance for this type of analysis, so I cannot advise as to whether this is a good approach to take.
For your second question, currently the functions in picante do require a community matrix to calculate MPD, MNTD, etc., so this would not work if you have only a distance matrix. In that case perhaps something like ape::dbrda would do what you are looking for?
