### ISSUE TITLE
Feature request: biplot for Inter-Community Mean Pairwise Distance for traits data

### ISSUE THREAD

**Issue by Jigyasa3** [skembel/picante#21]
Hey

Is it possible to plot a biplot for Inter-Community Mean Pairwise Distance for traits data? For example, to see which traits are driving the community difference.

**Comment by skembel** [comment]
Hello, if I understand the request it is possible to do this as a simple scatter plot.
`comm.dis <- comdist(comm, phylo.distances)`
`trait.dis <- comdist(comm, trait.distances)`
`plot(comm.dis, trait.dis)`
