### ISSUE TITLE
Phylogeny input file

### ISSUE THREAD

**Issue by carolinapinapaez** [skembel/picante#24]
Hi Steve, 

I have a very basic question about the phylogeny. After reviewing some literature, I've seen four types of trees that people uses as their phylogeny input files:

1. Pruned tree from an already published phylogeny (only contain species present in their site of study).
2. A published phylogeny where they added their species if not present (this can be a huge phylogeny, however, the species present in their city of study represent a small fraction of the big phylogeny).
3. Simple tree containing only one OTU/ species.
4. Tree containing one OTU/site, therefore, the tree will contain more than one sequence per OTU.

 Do you have a recommendation about the phylogeny approach?

I'm working with a genus of ectomycorrhizal fungi, the diversity of this genus is ~150 species.  In my study, I found 24 OTUS across all sampled sites.

**Comment by skembel** [comment]
Hi, sorry for the very slow reply. You need a single phylogeny that contains all of your OTUs, it does not matter if there are other species included in the phylogeny, they will be automatically pruned out when you calculate phylogenetic diversity etc. So your options 1 or 2 above would work.
