### ISSUE TITLE
Error in randomizeMatrix

### ISSUE THREAD

**Issue by Angelly057** [skembel/picante#32]
I'm new at this community. Hope you can help me, I've been trying to run an analysis of null models, I'm using a matrix of 2 places and approx 90 species, is an presence-absence matrix and I'm using null.model= richness, but I've also tried with other models and I keep getting this error:

Error in randomizeMatrix(t(dat2), null.model = "richness", iterations = 100) : 
  NA/NaN/Inf in foreign function call (arg 1)
In addition: Warning message:
In randomizeMatrix(t(dat2), null.model = "richness", iterations = 100) :
  NAs introduced by coercion

There's no blank spaces in the matrix, just 0 and 1.
I dont know whats my mistake.

**Comment by kerby1998** [comment]
Hi,  can you provide a reproducible example (that can be run directly within R console to troubleshoot)?

**Comment by kerby1998** [comment]
The problem does not seem to come from the package. You probably have NA, NaN, or Inf values in the dataset or one of the variables in the dataset is a character.  You can use str(df) to return the data type of each column in the data frame or use which(is.na(df)) to return the position of all NA in your dataset.

I will close the issue but if you need more help, you can send another one.
