### ISSUE TITLE
PD.ses for low sample sizes

### ISSUE THREAD

**Issue by abhitims** [skembel/picante#38]
Hi, 
I came across this paper and was curious if it is currently revised in picante. Although cases with less than 4 species are likely to be rare.

"Avoiding potential biases in ses.PD estimations with the Picante software package": https://www.biorxiv.org/content/10.1101/579300v1.full.pdf

Thank you.

Regards,
Abhishek

**Comment by skembel** [comment]
Hi, yes this was fixed, please see https://github.com/skembel/picante/issues/17
-Steve

**Comment by abhitims** [comment]
Oh great, sorry had missed that.

Thanks a bunch!
